### ISSUE TITLE
More than 20 reactions?

### ISSUE THREAD

**Issue by giles247** [finnreid19/Poll-Bot#13]
Just learned that basically not more than 20 people can vote due to reactions limit, which in my mind makes bot pretty useless. Does anyone know workaround for this?

**Comment by averagely** [comment]
You could use the strawpolls command to create a poll through https://www.strawpoll.me

**Comment by giles247** [comment]
yeah I know. was just hoping I might be wrong with the 20 reactions, but guess not.
thanks for reply

**Comment by averagely** [comment]
Oh I see. There can be more than 20 reactions, there just can't be more than 20 unique reactions (different emojis).

**Comment by averagely** [comment]
So more than 20 people can vote there just can't be more than 20 options

**Comment by giles247** [comment]
On poll I just did with 7 options it capped out at 20 people casting votes. After that no more reactions could be clicked.
