### ISSUE TITLE
Display zeros on fresh polls

### ISSUE THREAD

**Issue by diesocke** [finnreid19/Poll-Bot#17]
When I add a new poll, I expect the counts to start from zero. However, there is a greyed out 1, which leads to several misinterpretations. People think, someone would have voted on that option already.

Can the 1s be changed to 0s, please?

**Comment by averagely** [comment]
There isn't a way to start the polls from 0 because of the way reactions work on Discord.  Poll Bot must add reactions, just like a user, to messages in order to create a poll.  If you need the polls to start from 0 I suggest using strawpolls.
